
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class Categorize extends javax.swing.JFrame {

    /**
     * Creates new form Categorize
     */
    public Categorize() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCat = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "clothing", "grocery", "electronics", "food", "cosmetics" }));

        jLabel1.setText("Choose Category:");

        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Categorize");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel2.setText("Total expense for");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Platform", "Product Name", "Amount", "Quantity", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jCat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(250, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String catTot="0";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/osems","root","Subha03");
            
            if(jCat.getSelectedItem().equals("clothing")){
                String sql1 = "Select SUM(Amount*quantity) as Total from addexpense where CatId=1";
                PreparedStatement stm1 = con.prepareStatement(sql1);
                ResultSet rs = stm1.executeQuery();
                if (rs.next()) {
                    catTot = rs.getString("Total");
                }
                jLabel3.setText(jCat.getSelectedItem().toString());
                jLabel4.setText(catTot);
                
                String sql2 = "Select Platform,product_name,Amount,quantity,ExpenseDate from addexpense where CatId=1";
                PreparedStatement stm2 = con.prepareStatement(sql2);
                ResultSet rs2 = stm2.executeQuery();
                DefaultTableModel tb1 = (DefaultTableModel)jTable1.getModel();
                tb1.getDataVector().removeAllElements();
                while(rs2.next()){
                    String plat = rs2.getString("Platform");
                    String proname = rs2.getString("product_name");
                    String amt = rs2.getString("Amount");
                    String qty = rs2.getString("quantity");
                    String date = rs2.getString("ExpenseDate");
                    
                    String table1[] = new String[]{plat,proname,amt,qty,date};
                    
                    tb1.addRow(table1);
                }
            }
            else if(jCat.getSelectedItem().equals("grocery")){
                String sql1 = "Select SUM(Amount*quantity) as Total from addexpense where CatId=2";
                PreparedStatement stm1 = con.prepareStatement(sql1);
                ResultSet rs = stm1.executeQuery();
                if (rs.next()) {
                    catTot = rs.getString("Total");
                    
                }
                jLabel3.setText(jCat.getSelectedItem().toString());
                jLabel4.setText(catTot);
                String sql2 = "Select Platform,product_name,Amount,quantity,ExpenseDate from addexpense where CatId=2";
                PreparedStatement stm2 = con.prepareStatement(sql2);
                ResultSet rs2 = stm2.executeQuery();
                DefaultTableModel tb1 = (DefaultTableModel)jTable1.getModel();
                tb1.getDataVector().removeAllElements();
                while(rs2.next()){
                    String plat = rs2.getString("Platform");
                    String proname = rs2.getString("product_name");
                    String amt = rs2.getString("Amount");
                    String qty = rs2.getString("quantity");
                    String date = rs2.getString("ExpenseDate");
                    
                    String table1[] = new String[]{plat,proname,amt,qty,date};
                    
                    tb1.addRow(table1);
                }
            }
            else if(jCat.getSelectedItem().equals("electronics")){
                String sql1 = "Select SUM(Amount*quantity) as Total from addexpense where CatId=3";
                PreparedStatement stm1 = con.prepareStatement(sql1);
                ResultSet rs = stm1.executeQuery();
                if (rs.next()) {
                    catTot = rs.getString("Total");
                    
                }
                jLabel3.setText(jCat.getSelectedItem().toString());
                jLabel4.setText(catTot);
                String sql2 = "Select Platform,product_name,Amount,quantity,ExpenseDate from addexpense where CatId=3";
                PreparedStatement stm2 = con.prepareStatement(sql2);
                ResultSet rs2 = stm2.executeQuery();
                DefaultTableModel tb1 = (DefaultTableModel)jTable1.getModel();
                tb1.getDataVector().removeAllElements();
                while(rs2.next()){
                    String plat = rs2.getString("Platform");
                    String proname = rs2.getString("product_name");
                    String amt = rs2.getString("Amount");
                    String qty = rs2.getString("quantity");
                    String date = rs2.getString("ExpenseDate");
                    
                    String table1[] = new String[]{plat,proname,amt,qty,date};
                    tb1.addRow(table1);
                }
            }
            else if(jCat.getSelectedItem().equals("food")){
                String sql1 = "Select SUM(Amount*quantity) as Total from addexpense where CatId=4";
                PreparedStatement stm1 = con.prepareStatement(sql1);
                ResultSet rs = stm1.executeQuery();
                if (rs.next()) {
                    catTot = rs.getString("Total");
                    
                }
                jLabel3.setText(jCat.getSelectedItem().toString());
                jLabel4.setText(catTot);
                String sql2 = "Select Platform,product_name,Amount,quantity,ExpenseDate from addexpense where CatId=4";
                PreparedStatement stm2 = con.prepareStatement(sql2);
                ResultSet rs2 = stm2.executeQuery();
                DefaultTableModel tb1 = (DefaultTableModel)jTable1.getModel();
                tb1.getDataVector().removeAllElements();
                while(rs2.next()){
                    String plat = rs2.getString("Platform");
                    String proname = rs2.getString("product_name");
                    String amt = rs2.getString("Amount");
                    String qty = rs2.getString("quantity");
                    String date = rs2.getString("ExpenseDate");
                    
                    String table1[] = new String[]{plat,proname,amt,qty,date};
                   
                    tb1.addRow(table1);
                }
            }
            else{
                String sql1 = "Select SUM(Amount*quantity) as Total from addexpense where CatId=5";
                PreparedStatement stm1 = con.prepareStatement(sql1);
                ResultSet rs = stm1.executeQuery();
                if (rs.next()) {
                    catTot = rs.getString("Total");
                    
                }
                jLabel3.setText(jCat.getSelectedItem().toString());
                jLabel4.setText(catTot);
                String sql2 = "Select Platform,product_name,Amount,quantity,ExpenseDate from addexpense where CatId=5";
                PreparedStatement stm2 = con.prepareStatement(sql2);
                ResultSet rs2 = stm2.executeQuery();
                DefaultTableModel tb1 = (DefaultTableModel)jTable1.getModel();
                tb1.getDataVector().removeAllElements();
                while(rs2.next()){
                    String plat = rs2.getString("Platform");
                    String proname = rs2.getString("product_name");
                    String amt = rs2.getString("Amount");
                    String qty = rs2.getString("quantity");
                    String date = rs2.getString("ExpenseDate");
                    
                    String table1[] = new String[]{plat,proname,amt,qty,date};
                  
                    tb1.addRow(table1);
                }
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categorize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categorize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categorize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categorize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categorize().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
